# GNUmakefile

PACKAGE_DIR=../..
PACKAGE=$(notdir $(shell pwd))
$(PACKAGE)_TYPE = library

$(PACKAGE)_SWIFT_MODULES = \
	xsys core events streams CryptoSwift

include $(PACKAGE_DIR)/xcconfig/rules.make
