# GNUmakefile

PACKAGE_DIR=../..
PACKAGE=$(notdir $(shell pwd))
$(PACKAGE)_TYPE = testsuite

$(PACKAGE)_SWIFT_MODULES = xsys core events streams crypto CryptoSwift

include $(PACKAGE_DIR)/xcconfig/rules.make
