# GNUmakefile

PACKAGE_DIR=../..
PACKAGE=$(notdir $(shell pwd))

$(PACKAGE)_SWIFT_MODULES = \
  xsys core events streams fs console \
  process net http http_parser \
  Freddy json

include $(PACKAGE_DIR)/xcconfig/rules.make
