# GNUmakefile

NOZE_DIR=../..
PACKAGE=$(notdir $(shell pwd))

$(PACKAGE)_SWIFT_MODULES = \
  xsys core events dns streams fs console net process \
  http base64 http_parser

include $(NOZE_DIR)/xcconfig/rules.make
